# Scalar Vectors and Matrices

In [27]:
#To get above heading top Just under help you have code  click on code and change to heading

In [28]:
import numpy as np
#A scalar is a number, like 3, -5, 0.368, etc,
#Scalar means one number array 
s = 5
#Vectors
#Its nothing but Vector. Means single dimention matrix. 
 #A vector is a list of numbers (can be in a row or column),

v = np.array([5,-2,4])
v
type(v)
v.shape

s.shape
#you will get error. Why, s=-5 means integer. if matrics you will get results.
s_array.shape
#here  s_array = np.array(5) means its Array so you will get empty if you have 2*2 array you will get

#A matrix is an array of numbers (one or more rows, one or more columns).
m = np.array([[5,12,6],[-3,0,14]])
m
type(m)
m.shape


AttributeError: 'int' object has no attribute 'shape'

## Experiments

In [29]:
v.reshape(1,3)


array([[ 5, -2,  4]])

In [33]:
# shape array with 2 rows and 4 columns 
ar = np.arange(8).reshape(4 ,2) 
ar.shape
#but if you 

(4, 2)

In [30]:
#usually vector shape [5,2,4] so shape 1*3 but you can change to 3,1 also you can change 

array([ 5, -2,  4])

In [34]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [35]:
m+s
m+s_array
v+s
v
v+s_array
m+v

array([[10, 17, 11],
       [ 2,  5, 19]])