In [20]:
#please note as i said earlier scalar nothing but one element of matrix

In [ ]:
5+6
#its nothing but scalar
#vectors nothing but one dimentional array. v1 = np.array([1,2,3,4,5]) now v1 nothing but vector, but 90% u r using matrix or tensors


In [2]:
%%html 
<img src ="https://cdn.programiz.com/sites/tutorial2program/files/matrix.jpg", width=200, height=200>

In [ ]:
#above mentined nothing but matrix 4*3 matrix.

## Operations (Add, substract, divide)

In [3]:
import numpy as np
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[9,8,7],[1,3,-5]])

In [24]:
m1
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [23]:
m2 + np.array([1]) # i don't recommend this approach instead of that simply use m2 + 1

array([[10,  9,  8],
       [ 2,  4, -4]])

In [21]:
m1+1
m2+2

array([[11, 10,  9],
       [ 3,  5, -3]])

In [10]:
m1 + m2
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [6]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [7]:
m3

array([[ 5,  3],
       [-2,  4]])

In [8]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [9]:
m1 + m2
m3 - m4

#please note syze must same otherwise 

array([[-2,  8],
       [-5, -4]])

In [11]:
#you can do multi dimentions 3*3 array also

m5 = np.array([[22.33,-4.73],[-203.14,1200.02],[4.22,234.1]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02],
       [   4.22,  234.1 ]])

In [12]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [13]:
m5 - m6
m5 + m6

array([[ 153.46,  443.56],
       [-543.35, 1201.08],
       [  34.63,  659.09]])

In [ ]:
#samething you can apply for vectors also.. means vector nothing but one dimention array so its also like matrix so add, sub

In [16]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [ ]:
v1 + v2
v1 - v2

In [18]:
d = np.divide(m1, m2) 
d
dv = np.divide(v1,v2)
dv


array([0.2, 0.5, 1. , 2. , 5. ])

In [19]:
arr1 = [2, 27, 2, 21, 23] 
arr2 = [2, 3, 0, 5, 6] 

out = np.divide(arr1, arr2) 
#now third element you will get infinity .. why 2/0 is infinity thats y

C:\AITraining\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
