# Matrix Multiplication

In [10]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
res = np.dot(mat1,mat2) 
#Its called Dot product
res
#please note first matrix rows and second matrix columns column size must be match than only its processing
#you can also called like this
res=np.matmul(mat1,mat2)
res

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])

In [11]:
res = np.multiply(mat1,mat2)
res #multiply is different matrix multiply different

array([[  3,  24,  30],
       [ 15,  24,  56],
       [ 12, 672,  21]])

In [19]:
#please note first matrix rows and second matrix columns column size must be match than only its processing
C = np.array([[-12,5,-5,1,6],[6,-2,0,0,-3],[10,2,0,8,0],[9,-4,8,3,-6]])
D = np.array([[6,-1],[8,-4],[2,-2],[7,4],[-6,-9]])

np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])

In [ ]:
#one more important thing matrix multiplication not like matrix add, sub, divide, multiply its quite different..

## Transposing matrices

In [1]:
import numpy as np
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [2]:
A.T #Transpose Rows to columns columns to rows called Transpose

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [3]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [4]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [5]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [6]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

## Transposing scalars and Vectors

In [ ]:
s = np.array([5])

In [ ]:
s.T

In [17]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
x.T

In [ ]:
x.shape

In [ ]:
x_reshaped = x.reshape(1,3)
x_reshaped

In [ ]:
x_reshaped.T

# Other Multiplications

In [14]:
np.dot(5,6) # its nothing but scalar multiplication

30

In [15]:
np.dot(10,-2)

-20

In [18]:
#Scalar * Vector also you can do
x*5

array([ 5, 10, 15])